#!/bin/bash
mkdir -p /tmp/rom
cd /tmp/rom

cd ~
sudo apt install git aria2 -y
git clone https://gitlab.com/OrangeFox/misc/scripts
cd scripts
sudo bash setup/android_build_env.sh
sudo bash setup/install_android_sdk.sh

mkdir shrp
cd shrp
pwd
ls

#syncing repo
repo init -u git://github.com/SHRP/platform_manifest_twrp_omni.git -b v3_9.0
repo sync -j16

#cloning dt
git clone https://github.com/noobyysauraj/ofox_realme_RMX2151 device/realme/RMX2151

pwd
ls

export ALLOW_MISSING_DEPENDENCIES=true
. build/envsetup.sh
lunch omni_<device>-eng
mka recoveryimage

